---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/lpanza/ocp4-dr-demo-app-manifests.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
